### ISSUE TITLE
Installation fails with dependency error on inherits

### ISSUE THREAD

**Issue by jeffsx240** [growbrosops/containership-docs#1]
The instructions currently only list the 'npm install containership -g' step, but that will result in failed dependancies on a fresh install of Fedora 21. The installation requires the following steps.
1. sudo yum install npm make docker-io
2. npm install inherits containership -g 

To reproduce
HOST# docker run -ti fedora /bin/bash
CONTAINER# yum install npm make docker-io
CONTAINER# npm install containership -g

<output cut>
npm http 200 https://registry.npmjs.org/inherits/-/inherits-2.0.1.tgz
/usr/bin/containership -> /usr/lib/node_modules/containership/application.js
npm WARN unmet dependency /usr/lib/node_modules/block-stream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-ignore requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/fstream-npm requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/glob requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/npmconf requires inherits@'~2.0.0' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
npm WARN unmet dependency /usr/lib/node_modules/tar requires inherits@'2' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
containership@0.1.2 /usr/lib/node_modules/containership
├── daemon@1.1.0
├── lodash@2.4.1
├── nomnom@1.8.1 (underscore@1.6.0, chalk@0.4.0)
├── containership.api@0.1.0 (async@0.9.0, body-parser@1.10.0, express@4.10.5)
├── containership.scheduler@0.1.0 (flat@1.5.0, async@0.9.0, mkdirp@0.5.0, dockerode@2.0.6, forever-monitor@1.5.2)
├── containership.core@0.1.1 (async@0.8.0, body-parser@1.10.1, request@2.51.0, winston@0.7.3, praetor@0.0.6)
└── containership.cli@0.1.0 (flat@1.5.0, sprintf-js@0.0.7, colors@0.6.2, async@0.9.0, lodash@3.2.0, npm@2.2.0, request@2.51.0)

CONTAINER# npm install -g inherits
CONTAINER# npm install containership -g
Install completes

**Comment by normanjoyner** [comment]
I am able to reproduce this, but it appears the messages are just warnings. I am still able to run the `containership` executable without installing the `inherits` module globally as seen below:

```
bash-4.3# NODE_ENV=development containership agent --mode leader -l debug
info: Containership version 0.1.2 started in leader mode! source=containership.core
info: API is listening: http://0.0.0.0:8080 source=containership.api
warn: Invalid plugin path provided! source=containership.core
warn: ENOENT, no such file or directory '/root/.containership/plugins/node_modules' source=containership.core
info: Promoted to controlling leader! source=containership.core
verbose: Controlling cluster of 1 nodes source=containership.core
debug: Found leader node: fd6c7fa99ce1bf07 -> 8dfa58dece63 source=containership.core
info: Requesting application sync source=containership.core
info: Snapshotting applications succeeded source=containership.core
```

**Comment by jeffsx240** [comment]
Ran through it again, and you're right, the binary is there and seems to work. Closing.
